spring.application.name=vitalscans
spring.profiles.active=dev

# JWT Configuration
jwt.secret=vitalscan-secret-key-2024-spring-boot-jwt
jwt.expiration=86400000

# Server Configuration
server.port=5022
server.servlet.context-path=/collegeclinic

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
